# Archivo principal de configuración

# Tus credenciales de acceso para OCC
login:
  username: PON_AQUI_TU_USUARIO
  password: PON_AQUI_TU_CONTRASEÑA

# Los parámetros de búsqueda
search:
  # Este es el texto que va en "Qué tipo de talento buscas?"
  string: Alguien súper chido

  # El límite de CVs que vamos a buscar
  limit: 1000

  # Estos son los ids de los filtros del panel de lado izquierdo
  filters:
    - LOC-10
    - AGE-2
    - AGE-3
    - AL-5
    - AL-6
    - AL-7
    - SAL-1
    - SAL-2
